import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

export type Profile = 'standard' | 'strict';

export const GENERATED_MARKER =
    '# Generated by sallyport. Update with `npx sallyport init --upgrade`.';
export const WORKFLOWS_DIRECTORY = '.github/workflows';
export const CALLER_WORKFLOW_FILENAME = 'sallyport.yml';
export const CALLER_WORKFLOW_FILE = `${WORKFLOWS_DIRECTORY}/${CALLER_WORKFLOW_FILENAME}`;
export const STAGE_WORKFLOW = 'zsumz/sallyport/.github/workflows/stage.yml';
export const FINALIZE_WORKFLOW = 'zsumz/sallyport/.github/workflows/finalize.yml';
export const SIGNER_FINGERPRINT_LINE =
    '      signer_fingerprint: ${{ vars.SALLYPORT_SIGNER_FINGERPRINT }}';

export interface WorkflowPinRewrite {
    content: string;
    replaced: number;
}

const TEMPLATE_URL = new URL('../../templates/sallyport.yml', import.meta.url);
const SHA_TOKEN = '__SALLYPORT_SHA__';
const PROFILE_TOKEN = '__SALLYPORT_PROFILE__';
const SIGNER_TOKEN = '__SALLYPORT_SIGNER_FINGERPRINT__';
const TOKEN_PREFIX = '__SALLYPORT_';

// The CLI carries no runtime dependencies, so generated workflows are analyzed
// line by line instead of being parsed as YAML. Every pattern below is anchored
// to the exact shape this template emits.
const USES_PATTERN = /^\s*uses:\s*["']?([^"'\s]+)["']?\s*$/u;
const PROFILE_PATTERN = /^\s*profile:\s*["']?([A-Za-z0-9_-]+)["']?\s*$/u;
const PIN_PATTERN =
    /(zsumz\/sallyport\/\.github\/workflows\/(?:stage|finalize)\.yml)@[^\s"']+/gu;

export function sallyportTemplatePath(): string {
    return fileURLToPath(TEMPLATE_URL);
}

export async function readWorkflowTemplate(): Promise<string> {
    const file = sallyportTemplatePath();
    try {
        return await readFile(file, 'utf8');
    } catch {
        throw new Error(`Workflow generation failed: template ${file} is unreadable.`);
    }
}

export function renderCallerWorkflow(
    template: string,
    sha: string,
    profile: Profile,
): string {
    const withSigner = profile === 'strict'
        ? template.replaceAll(SIGNER_TOKEN, SIGNER_FINGERPRINT_LINE)
        : template.replaceAll(`${SIGNER_TOKEN}\n`, '');
    const rendered = withSigner
        .replaceAll(SHA_TOKEN, sha)
        .replaceAll(PROFILE_TOKEN, profile);
    if (rendered.includes(TOKEN_PREFIX)) {
        throw new Error(
            'Workflow generation failed: the template still contains unreplaced tokens.',
        );
    }
    if (!rendered.startsWith(GENERATED_MARKER)) {
        throw new Error(
            'Workflow generation failed: the template is missing the generated-by marker.',
        );
    }
    return rendered;
}

export function hasGeneratedMarker(content: string): boolean {
    return firstLine(content) === GENERATED_MARKER;
}

export function rewriteWorkflowPins(content: string, sha: string): WorkflowPinRewrite {
    const matches = content.match(PIN_PATTERN);
    return {
        content: content.replaceAll(PIN_PATTERN, `$1@${sha}`),
        replaced: matches === null ? 0 : matches.length,
    };
}

export function workflowUses(content: string): string[] {
    return content
        .split('\n')
        .map((line) => USES_PATTERN.exec(line)?.[1])
        .filter((value): value is string => value !== undefined);
}

export function workflowRef(content: string, workflow: string): string | null {
    const prefix = `${workflow}@`;
    const found = workflowUses(content).find((value) => value.startsWith(prefix));
    return found === undefined ? null : found.slice(prefix.length);
}

export function detectProfile(content: string): Profile {
    const profiles = content
        .split('\n')
        .map((line) => PROFILE_PATTERN.exec(line)?.[1]);
    return profiles.includes('strict') ? 'strict' : 'standard';
}

export function parseProfile(value: string): Profile {
    if (value !== 'standard' && value !== 'strict') {
        throw new Error(`Profile must be standard or strict, found ${value}.`);
    }
    return value;
}

function firstLine(content: string): string {
    return content.split('\n')[0]?.replace(/\r$/u, '') ?? '';
}
